### single with translation
GET {{host}}/characteristic/1a02151e-fa31-42df-8a55-318c6dd69334?lang=ua
Accept: application/json

### single with all translations
GET {{host}}/characteristic/raw/1a02151e-fa31-42df-8a55-318c6dd69334?lang=ua
Accept: application/json

### collection without search
GET {{host}}/characteristic/all/
Accept: application/json

### collection with search
GET {{host}}/characteristic/all/?filter[aliases][]=apartment_type&filter[aliases][]=localcode&filter[labels][]=Квартира
Accept: application/json

### inserting new characteristic
POST {{host}}/characteristic
Content-Type: application/json

{
  "attrName": "test",
  "i18n": {
    "ru": {
      "label": "test",
      "short": "test"
    },
    "ua": {
      "label": "test",
      "short": "test"
    }
  },
  "fieldType": "test",
  "measureUnit": "1",
  "property": {
    "search": {
      "sort": "1",
      "input": "asd",
      "types": ["00ff1b37-3060-4058-8377-4f9a0973bb5b", "17230889-2283-4ba69842-06a8d67f33a2"],
      "categories": ["7cb390e1-51af-43bc-95bf-d8d7ffa333ac", "7cb390e1-51af-43bc-95bf-d8d7ffa333ad"],
      "secret": true
    }
  }
}

### update characteristic
PUT {{host}}/characteristic/69835c9b-6622-4f76-ab66-53165da08aa7
Content-Type: application/json

{
  "attrName": "newattr2",
  "i18n": {
    "ru": {
      "label": "Новый аттр44",
      "short": "Новый44"
    },
    "ua": {
      "label": "Новий аттр44",
      "short": "Новмй44"
    }
  },
  "fieldType": "string",
  "measureUnit": "2",
  "property": {
    "search": {
      "sort": 12,
      "input": "text",
      "types": ["apartment"],
      "categories": ["service"],
      "secret": true
    }
  }
}

### remove characteristic
DELETE {{host}}/characteristic/bbd613ad-3c66-4f3e-bff6-f1ec79ef0dca?lang=ua
Accept: application/json

