### all chars with values for representation
GET {{host}}/representation/allchars/8d28c5b2-74c7-4a6e-864e-3fd1184411b3?lang=ua
Accept: application/json

### allc chars with values for representation by realty type
GET {{host}}/representation/byrealtytype/8d28c5b2-74c7-4a6e-864e-3fd1184411b3/house/?lang=ua
Accept: application/json

