### new chars with values for representation
POST {{host}}/repvalues
Content-Type: application/json
Accept: application/json

{
  "rep_uuid": "8d28c5b2-74c7-4a6e-864e-3fd1184411b3",
  "char_uuid": "949011cd-1b11-4fbf-8b0a-03205a092345",
  "char_values": [
    {
      "value_uuid": "d4e6f682-fd23-4f6d-8c41-2054c741f0bf",
      "sort": 3
    },
    {
      "value_uuid": "886302b3-5415-4fa3-b657-ff3c48c332f1",
      "sort": 4
    }
  ],
  "settings": {
    "rowId": 0,
    "rowOrder": 0,
    "types": [
      "apartment"
    ]
  }
}

### update chars with values for representation
PUT {{host}}/repvalues/28
Content-Type: application/json
Accept: application/json

{
  "rep_uuid": "8d28c5b2-74c7-4a6e-864e-3fd1184411b3",
  "char_uuid": "949011cd-1b11-4fbf-8b0a-03205a092345",
  "char_values": [
    {
      "value_uuid": "d4e6f682-fd23-4f6d-8c41-2054c741f0bf",
      "sort": 13
    },
    {
      "value_uuid": "886302b3-5415-4fa3-b657-ff3c48c332f1",
      "sort": 34
    }
  ],
  "settings": {
    "rowId": 0,
    "rowOrder": 0,
    "types": [
      "apartment"
    ]
  }
}


