### all chars with values for representation
GET {{host}}/rep/allchars/22dfa2fc-8b17-40bf-b9ca-cfca49f1aaf4?lang=ua
Accept: application/json

### all chars with values for representation by realty type
GET {{host}}/rep/byrealtytype/22dfa2fc-8b17-40bf-b9ca-cfca49f1aaf4/house/?lang=ua
Accept: application/json

### all chars with values for represenattion of special search type and realty type
GET {{host}}/rep/bysearchtype/22dfa2fc-8b17-40bf-b9ca-cfca49f1aaf4/secret/?realtyType=apartment&lang=ua
Accept: application/json

### all chars with values for represenattion for special characteristic
GET {{host}}/rep/bychar/22dfa2fc-8b17-40bf-b9ca-cfca49f1aaf4/1a02151e-fa31-42df-8a55-318c6dd69334
Accept: application/json

