### new chars with values for representation
POST {{host}}/repvalues
Content-Type: application/json
Accept: application/json

{
  "rep_uuid": "00f1e3d2-7c76-429c-ad6e-0c0d87642505",
  "char_uuid": "1a02151e-fa31-42df-8a55-318c6dd69334",
  "char_values": [
    {
      "value_uuid": "00ed2ea1-0b08-4dd8-99ae-0f11720fb97a",
      "sort": 3
    },
    {
      "value_uuid": "12894331-d28e-4d8b-a71a-4849dc47de04",
      "sort": 4
    }
  ],
  "settings": {
    "rowId": 0,
    "rowOrder": 0
  }
}

### update chars with values for representation
PUT {{host}}/repvalues/5071
Content-Type: application/json
Accept: application/json

{
  "rep_uuid": "22dfa2fc-8b17-40bf-b9ca-cfca49f1aaf4",
  "char_uuid": "13908407-cb74-4bd8-bb24-be207473b24f",
  "char_values": [
    {
      "value_uuid": "12894331-d28e-4d8b-a71a-4849dc47de04",
      "sort": 13
    },
    {
      "value_uuid": "00ed2ea1-0b08-4dd8-99ae-0f11720fb97a",
      "sort": 30
    },
    {
      "value_uuid": "80b2bd55-f228-4d2e-9028-21ca528c9634",
      "sort": 37
    }
  ],
  "settings": {
    "rowId": 0,
    "rowOrder": 0
  }
}

### remove chars with values
DELETE {{host}}/repvalues/20709
Accept: application/json

### Get chars of the representation
GET {{host}}/rep/bychar/30007f41-7c2d-4849-8306-fddfbb6bf18a/9f2240e4-c8aa-42df-8076-f078d9d94353
Accept: application/json


