### inserting new value to characteristic
POST {{host}}/value
Content-Type: application/json

{
  "fk_char": "1a02151e-fa31-42df-8a55-318c6dd69334",
  "i18n": {
    "ru": {
      "label": "Новое значение"
    },
    "ua": {
      "label": "Нове значення"
    }
  },
  "key": 23,
  "default_sort": 1,
  "only_type": [
    "apartment",
    "house"
  ]
}

### update value
PUT {{host}}/value/eccb4388-10c6-4f12-8d5d-ff73b771adb1
Content-Type: application/json

{
  "fk_char": "1a02151e-fa31-42df-8a55-318c6dd69334",
  "i18n": {
    "ru": {
      "label": "Отредактировано"
    },
    "ua": {
      "label": "Відредактовано"
    }
  },
  "key": 12,
  "default_sort": 1,
  "only_type": [
    "apartment",
    "commercial"
  ]
}

### Deleting value of characteristic
DELETE {{host}}/value/eccb4388-10c6-4f12-8d5d-ff73b771adb1
Content-Type: application/json

### single value by uuid with translation
GET {{host}}/value/eccb4388-10c6-4f12-8d5d-ff73b771adb1?lang=ua
Accept: application/json

