doctrine:
    dbal:
        override_url: true
        url: '%env(resolve:DATABASE_URL)%'
        types:
            uuid: Symfony\Bridge\Doctrine\Types\UuidType
            I18nCharDbType: App\Entity\OrmTypes\I18nCharDbType
            I18nCharValueDbType: App\Entity\OrmTypes\I18nValueDbType
            CharSearchPropertyType: App\Entity\OrmTypes\CharSearchPropertyDbType
            CharType: App\Entity\OrmTypes\CharTypeDbType
            RealtyTypesDbType: App\Entity\OrmTypes\RealtyTypes
            JsonbForTrashDbType: App\Entity\OrmTypes\JsonbForTrashDbType


        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
        dql:
            string_functions:
                JSON_EXTRACT_PATH: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Postgresql\JsonExtractPath
                JSON_GET_TEXT: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Postgresql\JsonGetText
                JSON_GET: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Postgresql\JsonGet
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
