nelmio_api_doc:
    documentation:
        servers:
            - url: https://vec.chars
              description: API over HTTPS
        info:
            title: Сервис характеристик
            description: Централизованное хранилище характеристик объекта недвижимости
            version: 0.0.1-alpha
        tags:
            - { name: Характеристики, description: Функционал по управлению характеристиками }
            - { name: Наборы для представительств, description: Функционал для выбора характеристик и их значений на основе представительства }
            - { name: Словарные данные, description: Функционал для обработки словарного значения }
        components:
            parameters:
                Language:
                    in: query
                    name: lang
                    description: Язык приложения
                    schema:
                        type: string
                        enum: ["ua", "ru"]
                        example: ua
                PathUuid:
                    in: path
                    name: uuid
                    description: Uuid объекта
                    required: true
                    schema:
                        type: string
                        example: 1a02151e-fa31-42df-8a55-318c6dd69334
                PathId:
                    in: path
                    name: id
                    description: ID объекта
                    required: true
                    schema:
                        type: integer
                        example: 1
                PathUuidRepresentation:
                    in: path
                    name: repUuid
                    description: Uuid представительства
                    required: true
                    schema:
                        type: string
                        example: 22dfa2fc-8b17-40bf-b9ca-cfca49f1aaf4
                PathUuidChar:
                    in: path
                    name: charUuid
                    description: Uuid характеристики
                    required: true
                    schema:
                        type: string
                        example: 1a02151e-fa31-42df-8a55-318c6dd69334
            responses:
                NotFound:
                    description: Document not found
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorDto'
                ValidationFailed:
                    description: Bad request
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorDto'
                Accepted:
                    description: Request is accepted
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Response202Dto'
            requestBodies:
                CharsUpsert:
                    description: Payload для создания, обновления характеристики
                    required: true
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/UpsertCharacteristic'
                UpsertMeasureUnit:
                    description: Payload для создания, обновления единицы измерения
                    required: true
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/UpsertMeasureUnit'
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
            schemas:
                RealtyTypeEnum:
                    type: string
                    example: apartment
                    description: Тип недвижимости
                    enum:
                        - apartment
                        - house
                        - commercial
                        - apartment_complex
                DataTypeEnum:
                    type: string
                    example: string
                    description: Тип данных для хранения в БД
                    enum:
                        - string
                        - fk
                        - int
                        - float
                        - boolean
                        - array
                        - json
                SearchCategoryEnum:
                    type: string
                    example: secret
                    description: Категории поиска
                    enum:
                        - secret
                        - main
                        - service
                        - additional
                        - rent
                        - servicebuyer
        security:
            - Bearer: []
    areas: # to filter documented areas
        path_patterns:
#            - ^/api/v1/(?!/doc.json$) # Accepts routes under /api except /api/doc
             - ^/characteristic/*
             - ^/rep*
             - ^/value*
             - ^/units*
    models:
        names:
            - { alias: ErrorDto, type: App\dto\ErrorDto }
            - { alias: UpsertCharacteristic, type: App\dto\UpsertCharacteristic }
            - { alias: UpsertMeasureUnit, type: App\dto\UpsertMeasureUnit }
            - { alias: Response202Dto, type: App\dto\Response202Dto }
