apiVersion: v1
kind: PersistentVolume
metadata:
  name: chars-db-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: '/var/lib/chars-postgres/data'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chars-db-pvc
spec:
  volumeName: chars-db-pv
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
