apiVersion: v1
kind: Service
metadata:
  name: chars-srv
spec:
  selector:
    app: chars
  ports:
    - port: 3000
      targetPort: 80
      protocol: TCP
      name: php-chars-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-depl
spec:
  selector:
    matchLabels:
      app: chars
  template:
    metadata:
      labels:
        app: chars
    spec:
      containers:
        - name: nginx
          image: nginx:1.19-alpine
          volumeMounts:
            - name: shared-files
              mountPath: /var/www/html
            - name: nginx-conf-volume
              mountPath: /etc/nginx/templates
        - name: php-chars
          image: atlanta/chars
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@chars-postgres-srv:5432/chars?serverVersion=10&charset=utf8"
          volumeMounts:
            - mountPath: /var/www/html
              name: shared-files
            - name: php-conf-volume
              mountPath: /usr/local/etc/php/conf.d/php.ini
              subPath: php.config

      volumes:
        - name: nginx-conf-volume
          hostPath:
            path: /home/evgeniy/WebstormProjects/ms_chars/k8s_config/conf/nginx/templates

        - name: php-conf-volume
          configMap:
            name: php-config

        - name: shared-files
          hostPath:
            path: /home/evgeniy/WebstormProjects/ms_chars