#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#app_services_step_get:
#  path: step/get/{serviceId}
#  methods: GET
#  controller: App\Controller\v1\StepsController::getSteps
#  requirements:
#    serviceId: '\d+'
#    format: json

app.swagger:
  path: /api/v1/chars/doc.json
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger }

controllers:
  resource: '../src/Controller/v1/'
  type: annotation
  prefix: '/api/v1/chars'
  name_prefix: 'v1_'
  trailing_slash_on_root: false
# exclude: '../../src/Controller/v2'

